//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBotLib.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBotLib.Locales.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or sets the activity.
        /// </summary>
        public static string Settings_Activity_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the activity is set to: {type} {name}..
        /// </summary>
        public static string Settings_Activity_Get {
            get {
                return ResourceManager.GetString("Settings.Activity.Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current activity.
        /// </summary>
        public static string Settings_Activity_Get_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Get.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity is set to: {type} {name}..
        /// </summary>
        public static string Settings_Activity_Get_dm {
            get {
                return ResourceManager.GetString("Settings.Activity.Get_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the activity is currently not set..
        /// </summary>
        public static string Settings_Activity_Get_Empty {
            get {
                return ResourceManager.GetString("Settings.Activity.Get.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity is currently not set..
        /// </summary>
        public static string Settings_Activity_Get_Empty_dm {
            get {
                return ResourceManager.GetString("Settings.Activity.Get.Empty_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the activity has been set to: {type} {name}..
        /// </summary>
        public static string Settings_Activity_Set {
            get {
                return ResourceManager.GetString("Settings.Activity.Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the activity.
        /// </summary>
        public static string Settings_Activity_Set_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Set.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity has been set to: {type} {name}..
        /// </summary>
        public static string Settings_Activity_Set_dm {
            get {
                return ResourceManager.GetString("Settings.Activity.Set_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, that activity type is invalid. It needs to be one of the following: Playing, Streaming, Listening, Watching..
        /// </summary>
        public static string Settings_Activity_Set_InvalidType {
            get {
                return ResourceManager.GetString("Settings.Activity.Set.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That activity type is invalid. It needs to be one of the following: Playing, Streaming, Listening, Watching..
        /// </summary>
        public static string Settings_Activity_Set_InvalidType_dm {
            get {
                return ResourceManager.GetString("Settings.Activity.Set.InvalidType_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity description.
        /// </summary>
        public static string Settings_Activity_Set_Text_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Set.Text.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type: Playing, Streaming, Listening, Watching.
        /// </summary>
        public static string Settings_Activity_Set_Type_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Set.Type.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the activity has been removed..
        /// </summary>
        public static string Settings_Activity_Unset {
            get {
                return ResourceManager.GetString("Settings.Activity.Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the activity.
        /// </summary>
        public static string Settings_Activity_Unset_Description {
            get {
                return ResourceManager.GetString("Settings.Activity.Unset.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity has been removed..
        /// </summary>
        public static string Settings_Activity_Unset_dm {
            get {
                return ResourceManager.GetString("Settings.Activity.Unset_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Description {
            get {
                return ResourceManager.GetString("Settings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global language is set to {langName} ({langKey})..
        /// </summary>
        public static string Settings_GetLanguageGlobal {
            get {
                return ResourceManager.GetString("Settings.GetLanguageGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the server language is set to {langName} ({langKey})..
        /// </summary>
        public static string Settings_GetLanguageGuild {
            get {
                return ResourceManager.GetString("Settings.GetLanguageGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the command prefix is set to `{prefix}`..
        /// </summary>
        public static string Settings_GetPrefix {
            get {
                return ResourceManager.GetString("Settings.GetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the command prefix is currently not set..
        /// </summary>
        public static string Settings_GetPrefix_Empty {
            get {
                return ResourceManager.GetString("Settings.GetPrefix.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or sets the language.
        /// </summary>
        public static string Settings_Language_Description {
            get {
                return ResourceManager.GetString("Settings.Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current global language.
        /// </summary>
        public static string Settings_Language_GetGlobal_Description {
            get {
                return ResourceManager.GetString("Settings.Language.GetGlobal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current language for this server.
        /// </summary>
        public static string Settings_Language_GetGuild_Description {
            get {
                return ResourceManager.GetString("Settings.Language.GetGuild.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the global language.
        /// </summary>
        public static string Settings_Language_SetGlobal_Description {
            get {
                return ResourceManager.GetString("Settings.Language.SetGlobal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language id.
        /// </summary>
        public static string Settings_Language_SetGlobal_LangId_Description {
            get {
                return ResourceManager.GetString("Settings.Language.SetGlobal.LangId.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the server language.
        /// </summary>
        public static string Settings_Language_SetGuild_Description {
            get {
                return ResourceManager.GetString("Settings.Language.SetGuild.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language id.
        /// </summary>
        public static string Settings_Language_SetGuild_LangId_Description {
            get {
                return ResourceManager.GetString("Settings.Language.SetGuild.LangId.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or sets the command prefix.
        /// </summary>
        public static string Settings_Prefix_Description {
            get {
                return ResourceManager.GetString("Settings.Prefix.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the current command prefix.
        /// </summary>
        public static string Settings_Prefix_Get_Description {
            get {
                return ResourceManager.GetString("Settings.Prefix.Get.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the command prefix.
        /// </summary>
        public static string Settings_Prefix_Set_Description {
            get {
                return ResourceManager.GetString("Settings.Prefix.Set.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command prefix.
        /// </summary>
        public static string Settings_Prefix_Set_Prefix_Description {
            get {
                return ResourceManager.GetString("Settings.Prefix.Set.Prefix.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global language has been set to {langName}..
        /// </summary>
        public static string Settings_SetLanguageGlobal {
            get {
                return ResourceManager.GetString("Settings.SetLanguageGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language {langKey} is not a valid language for the bot..
        /// </summary>
        public static string Settings_SetLanguageGlobal_NotAvailable {
            get {
                return ResourceManager.GetString("Settings.SetLanguageGlobal.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the server language has been set to {langName}..
        /// </summary>
        public static string Settings_SetLanguageGuild {
            get {
                return ResourceManager.GetString("Settings.SetLanguageGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the language {langKey} is not a valid language for the bot..
        /// </summary>
        public static string Settings_SetLanguageGuild_NotAvailable {
            get {
                return ResourceManager.GetString("Settings.SetLanguageGuild.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the command prefix has been set to `{prefix}`..
        /// </summary>
        public static string Settings_SetPrefix {
            get {
                return ResourceManager.GetString("Settings.SetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the command prefix has been removed..
        /// </summary>
        public static string Settings_SetPrefix_Empty {
            get {
                return ResourceManager.GetString("Settings.SetPrefix.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utils_Description {
            get {
                return ResourceManager.GetString("Utils.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, listed below are the available commands. You can append the name of a command to this help command for more information about that command..
        /// </summary>
        public static string Utils_Help {
            get {
                return ResourceManager.GetString("Utils.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, the command information is as follows:.
        /// </summary>
        public static string Utils_Help_Command {
            get {
                return ResourceManager.GetString("Utils.Help.Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command information is as follows:.
        /// </summary>
        public static string Utils_Help_Command_dm {
            get {
                return ResourceManager.GetString("Utils.Help.Command_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user:mention}, that command does not exist..
        /// </summary>
        public static string Utils_Help_Command_DoesNotExist {
            get {
                return ResourceManager.GetString("Utils.Help.Command.DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That command does not exist..
        /// </summary>
        public static string Utils_Help_Command_DoesNotExist_dm {
            get {
                return ResourceManager.GetString("Utils.Help.Command.DoesNotExist_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This command has extra subcommands available:*.
        /// </summary>
        public static string Utils_Help_Command_Sub {
            get {
                return ResourceManager.GetString("Utils.Help.Command.Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{commandInvocation}` - {description}.
        /// </summary>
        public static string Utils_Help_CommandPart {
            get {
                return ResourceManager.GetString("Utils.Help.CommandPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about the commands.
        /// </summary>
        public static string Utils_Help_Description {
            get {
                return ResourceManager.GetString("Utils.Help.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed below are the available commands. You can append the name of a command to this help command for more information about that command..
        /// </summary>
        public static string Utils_Help_dm {
            get {
                return ResourceManager.GetString("Utils.Help_dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands with subcommands: *{submodules}*..
        /// </summary>
        public static string Utils_Help_Module_Submodules {
            get {
                return ResourceManager.GetString("Utils.Help.Module.Submodules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __**{description}**__.
        /// </summary>
        public static string Utils_Help_ModulePart {
            get {
                return ResourceManager.GetString("Utils.Help.ModulePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command.
        /// </summary>
        public static string Utils_Help_Single_Command_Description {
            get {
                return ResourceManager.GetString("Utils.Help.Single.Command.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about a command.
        /// </summary>
        public static string Utils_Help_Single_Description {
            get {
                return ResourceManager.GetString("Utils.Help.Single.Description", resourceCulture);
            }
        }
    }
}
