version: "3"
services:
  db:
    image: "mongo:${MONGO_VER}"
    restart: unless-stopped
    volumes:
      - ./storage/configdb:/data/configdb
      - ./storage/db:/data/db
  redis:
    image: "redis:${REDIS_VER}-alpine"
    restart: unless-stopped
    volumes:
      - ./storage/cache:/data
  bot:
    image: "archomeda/raiders-inn-bot:${BOT_VER}"
    restart: unless-stopped
    volumes:
      - ./config:/bot/config
    links:
      - db
      - redis
    environment:
      MONGO_URI: mongodb://db/raiders-inn-discord-bot
